
### USERS
drop_users="DROP TABLE IF EXISTS USERS CASCADE"
create_users="CREATE TABLE IF NOT EXISTS USERS(USER_ID INT, FIRST_NAME TEXT, LAST_NAME TEXT, GENDER TEXT, LEVEL TEXT, PRIMARY KEY(USER_ID, LEVEL))"

### ARTISTS
drop_artists = "DROP TABLE IF EXISTS ARTISTS CASCADE"
create_artists = "CREATE TABLE IF NOT EXISTS ARTISTS(idArtist BIGSERIAL PRIMARY KEY, ARTIST_ID TEXT UNIQUE, NAME TEXT, LOCATION TEXT, LATITUDE TEXT, LONGITUDE TEXT)"

### SONGS
drop_songs="DROP TABLE IF EXISTS SONGS CASCADE"
create_songs="CREATE TABLE IF NOT EXISTS SONGS(idSong BIGSERIAL PRIMARY KEY, SONG_ID TEXT UNIQUE, TITLE TEXT, ARTIST_ID TEXT, YEAR INT, DURATION FLOAT)"

### TIME
drop_time = "DROP TABLE IF EXISTS TIME CASCADE"
create_time = "CREATE TABLE IF NOT EXISTS TIME(START_TIME TIMESTAMP, HOUR INT, DAY INT, WEEK INT, MONTH INT, YEAR INT, WEEKDAY TEXT)"

### SONGPLAYS
drop_songplays="DROP TABLE IF EXISTS SONGPLAYS CASCADE"
create_songplays="CREATE TABLE IF NOT EXISTS SONGPLAYS(SONGPLAY_ID BIGSERIAL PRIMARY KEY, START_TIME TIMESTAMP, USER_ID INT, LEVEL TEXT, idSong INT, idArtist INT, SESSION_ID INT, LOCATION TEXT, USER_AGENT TEXT)"

list_drop_tables = [drop_users, drop_artists, drop_songs, drop_time, drop_songplays]
list_create_tables = [create_users, create_artists, create_songs, create_time, create_songplays]